changed config

diff --git a/.semaphore/run-tests-cloud.yml b/.semaphore/run-tests-cloud.yml
--- a/.semaphore/run-tests-cloud.yml
+++ b/.semaphore/run-tests-cloud.yml
@@ -144,32 +144,34 @@ blocks:
                 cd /tmp && git clone https://github.com/confluentinc/librdkafka.git
                 cd /tmp/librdkafka && git checkout k2_testing_final
                 
-                echo "Building librdkafka with dev-conf.sh..."
-                ./dev-conf.sh
+                echo "Building test harness from k2_testing_final..."
+                ./configure --enable-ssl
+                make
+                cd tests && make
+                cd /tmp/librdkafka
                 
-                # Build specific version if LIBRDKAFKA_VERSION is set
-                if [[ -n "$LIBRDKAFKA_VERSION" ]]; then
-                  echo "Building librdkafka version: ${LIBRDKAFKA_VERSION}"
-                  mkdir -p /tmp/librd_ver
-                  cd /tmp/librd_ver && git clone https://github.com/confluentinc/librdkafka.git
-                  cd /tmp/librd_ver/librdkafka && git checkout ${LIBRDKAFKA_VERSION}
-                  ./configure --enable-ssl
-                  make
-                  sudo make install
-                  echo "Custom librdkafka version built at /tmp/librd_ver/librdkafka"
-                fi
+                # Build the specific librdkafka version to test
+                echo "Building librdkafka version ${LIBRDKAFKA_VERSION} for testing..."
+                mkdir -p /tmp/librd_ver
+                cd /tmp/librd_ver && git clone https://github.com/confluentinc/librdkafka.git
+                cd /tmp/librd_ver/librdkafka && git checkout ${LIBRDKAFKA_VERSION}
+                ./configure --enable-ssl
+                make
+                sudo make install
                 
                 echo "Creating test.conf..."
-                echo "security.protocol=SASL_SSL" > /tmp/librdkafka/tests/test.conf
-                echo "sasl.mechanism=PLAIN" >> /tmp/librdkafka/tests/test.conf
-                echo "sasl.username=${API_KEY}" >> /tmp/librdkafka/tests/test.conf
-                echo "sasl.password=${API_SECRET}" >> /tmp/librdkafka/tests/test.conf
-                echo "ssl.endpoint.identification.algorithm=none" >> /tmp/librdkafka/tests/test.conf
-                echo "test.timeout.multiplier=5" >> /tmp/librdkafka/tests/test.conf
-                echo "test.topic.prefix=njc-test-" >> /tmp/librdkafka/tests/test.conf
-                echo "test.topic.random=true" >> /tmp/librdkafka/tests/test.conf
-                echo "metadata.broker.list=${BOOTSTRAP_SERVER}" >> /tmp/librdkafka/tests/test.conf
-                echo "test.sleep.multiplier=2.0" >> /tmp/librdkafka/tests/test.conf
+                printf '%s\n' \
+                  "security.protocol=SASL_SSL" \
+                  "sasl.mechanism=PLAIN" \
+                  "sasl.username=${API_KEY}" \
+                  "sasl.password=${API_SECRET}" \
+                  "ssl.endpoint.identification.algorithm=none" \
+                  "test.timeout.multiplier=5" \
+                  "test.topic.prefix=njc-test-" \
+                  "test.topic.random=true" \
+                  "metadata.broker.list=${BOOTSTRAP_SERVER}" \
+                  "test.sleep.multiplier=2.0" \
+                  > /tmp/librdkafka/tests/test.conf
               fi
             - |
               if [[ "$KAFKA_TYPE" == "k2" ]]; then
@@ -215,29 +217,28 @@ blocks:
                 '
                 kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c 'cd /tmp && git clone https://github.com/confluentinc/librdkafka.git'
                 kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c 'cd /tmp/librdkafka && git checkout k2_testing_final'
-                kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c 'cd /tmp/librdkafka && ./dev-conf.sh'
+                kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c 'cd /tmp/librdkafka && ./configure --enable-ssl && make && cd tests && make'
                 
-                # Build specific version if LIBRDKAFKA_VERSION is set
-                if [[ -n "$LIBRDKAFKA_VERSION" ]]; then
-                  echo "Building librdkafka version: ${LIBRDKAFKA_VERSION} in pod"
-                  kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c 'mkdir -p /tmp/librd_ver && cd /tmp/librd_ver && git clone https://github.com/confluentinc/librdkafka.git'
-                  kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c "cd /tmp/librd_ver/librdkafka && git checkout ${LIBRDKAFKA_VERSION}"
-                  kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c 'cd /tmp/librd_ver/librdkafka && ./configure --enable-ssl && make && make install'
-                fi
+                echo "Building librdkafka version ${LIBRDKAFKA_VERSION} in pod..."
+                kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c 'mkdir -p /tmp/librd_ver && cd /tmp/librd_ver && git clone https://github.com/confluentinc/librdkafka.git'
+                kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c "cd /tmp/librd_ver/librdkafka && git checkout ${LIBRDKAFKA_VERSION}"
+                kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c 'cd /tmp/librd_ver/librdkafka && ./configure --enable-ssl && make && make install'
 
-                echo "security.protocol=SASL_SSL" > /tmp/test.conf
-                echo "sasl.mechanism=PLAIN" >> /tmp/test.conf
-                echo "sasl.username=${API_KEY}" >> /tmp/test.conf
-                echo "sasl.password=${API_SECRET}" >> /tmp/test.conf
-                echo "ssl.endpoint.identification.algorithm=none" >> /tmp/test.conf
-                echo "test.timeout.multiplier=20" >> /tmp/test.conf
-                echo "test.topic.prefix=njc-test-" >> /tmp/test.conf
-                echo "test.topic.random=true" >> /tmp/test.conf
-                echo "metadata.broker.list=${BOOTSTRAP_SERVER}" >> /tmp/test.conf
-                echo "test.supported.acks=-1" >> /tmp/test.conf
-                echo "test.sleep.multiplier=3.0" >> /tmp/test.conf
-                echo "test.skip.idempotent=true" >> /tmp/test.conf
-                echo "test.skip.numbers=0011,0059,0081" >> /tmp/test.conf
+                printf '%s\n' \
+                  "security.protocol=SASL_SSL" \
+                  "sasl.mechanism=PLAIN" \
+                  "sasl.username=${API_KEY}" \
+                  "sasl.password=${API_SECRET}" \
+                  "ssl.endpoint.identification.algorithm=none" \
+                  "test.timeout.multiplier=20" \
+                  "test.topic.prefix=njc-test-" \
+                  "test.topic.random=true" \
+                  "metadata.broker.list=${BOOTSTRAP_SERVER}" \
+                  "test.supported.acks=-1" \
+                  "test.sleep.multiplier=3.0" \
+                  "test.skip.idempotent=true" \
+                  "test.skip.numbers=0011,0059,0081" \
+                  > /tmp/test.conf
                 kubectl --context ${K8S_CONTEXT} cp /tmp/test.conf ${TOOLBOX_POD}:/tmp/librdkafka/tests/test.conf
                 rm -f /tmp/test.conf
               fi
@@ -247,21 +248,12 @@ blocks:
                 cd /tmp/librdkafka/tests
                 echo "Current directory: $(pwd)"
                 echo "test.conf exists: $(test -f test.conf && echo yes || echo no)"
-                if [[ -n "$LIBRDKAFKA_VERSION" ]]; then
-                  echo "Running tests with librdkafka version: ${LIBRDKAFKA_VERSION}"
-                  LD_PRELOAD="/tmp/librd_ver/librdkafka/src-cpp/librdkafka++.so:/tmp/librd_ver/librdkafka/src/librdkafka.so" \
-                  LD_LIBRARY_PATH="/tmp/librd_ver/librdkafka/src-cpp:/tmp/librd_ver/librdkafka/src:$LD_LIBRARY_PATH" \
-                  TESTS=0001 ./run-test.sh || echo "Tests finished with failures"
-                else
-                  TESTS=0001 ./run-test.sh || echo "Tests finished with failures"
-                fi
+                echo "Running tests with librdkafka ${LIBRDKAFKA_VERSION}..."
+                LD_PRELOAD="/tmp/librd_ver/librdkafka/src-cpp/librdkafka++.so:/tmp/librd_ver/librdkafka/src/librdkafka.so" \
+                LD_LIBRARY_PATH="/tmp/librd_ver/librdkafka/src-cpp:/tmp/librd_ver/librdkafka/src:$LD_LIBRARY_PATH" \
+                TESTS=0001 ./run-test.sh || echo "Tests finished with failures"
               else
                 export TOOLBOX_POD="njc-test-pod-${SEMAPHORE_JOB_ID}"
-                echo "Executing tests in pod ${TOOLBOX_POD}..."
-                if [[ -n "$LIBRDKAFKA_VERSION" ]]; then
-                  echo "Running tests with librdkafka version: ${LIBRDKAFKA_VERSION}"
-                  kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c "cd /tmp/librdkafka/tests && LD_PRELOAD='/tmp/librd_ver/librdkafka/src-cpp/librdkafka++.so:/tmp/librd_ver/librdkafka/src/librdkafka.so' LD_LIBRARY_PATH='/tmp/librd_ver/librdkafka/src-cpp:/tmp/librd_ver/librdkafka/src:\$LD_LIBRARY_PATH' TESTS=0001 ./run-test.sh" || echo "Tests finished with failures"
-                else
-                  kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c "cd /tmp/librdkafka/tests && TESTS=0001 ./run-test.sh" || echo "Tests finished with failures"
-                fi
+                echo "Executing tests in pod ${TOOLBOX_POD} with librdkafka ${LIBRDKAFKA_VERSION}..."
+                kubectl --context ${K8S_CONTEXT} exec ${TOOLBOX_POD} -- bash -c "cd /tmp/librdkafka/tests && LD_PRELOAD='/tmp/librd_ver/librdkafka/src-cpp/librdkafka++.so:/tmp/librd_ver/librdkafka/src/librdkafka.so' LD_LIBRARY_PATH='/tmp/librd_ver/librdkafka/src-cpp:/tmp/librd_ver/librdkafka/src:\$LD_LIBRARY_PATH' TESTS=0001 ./run-test.sh" || echo "Tests finished with failures"
               fi                              
